### ISSUE TITLE
Best practice to clear all tables in Rails

### ISSUE THREAD

**Issue by liormb** [liormb/NewStand#1]
After seeding my database's tables, I'm trying to clear them but without no success.

In db/seeds.rb file:

namespace :db do
  desc "clear the databse"
  task :clear do 
    User.delete_all
    Group.delete_all
    UsersGroup.delete_all
  end
end

But I'm getting this error:

$ rake db:clear --trace
rake aborted!
Don't know how to build task 'db:clear'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/gems/rake-10.1.1/lib/rake/task_manager.rb:49:in `[]'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/gems/rake-10.1.1/lib/rake/application.rb:148:in`invoke_task'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/gems/rake-10.1.1/lib/rake/application.rb:106:in`each'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/gems/rake-10.1.1/lib/rake/application.rb:115:in`run_with_threads'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/gems/rake-10.1.1/lib/rake/application.rb:78:in`block in run'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/gems/rake-10.1.1/lib/rake/application.rb:75:in`run'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/bin/rake:23:in`load'
/Users/liormb/.rvm/gems/ruby-2.0.0-p247@block_rails_3/bin/rake:23:in `<main>'

**Comment by MikeSofaer** [comment]
That needs to go in /lib/tasks/db.rake

**Comment by liormb** [comment]
Look like some initializing is missing... 
How to initialize all my models?

$ rake db:clear
rake aborted!
uninitialized constant User
/Users/liormb/Documents/ga_wdi/projects/newstand/lib/tasks/db.rake:5:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:clear
(See full trace by running task with --trace)

**Comment by MikeSofaer** [comment]
Try
require File.expand_path("../../../config/environment", **FILE**)

**Comment by liormb** [comment]
Find the solution: I needed to add the environment as a property to my task like so: task :clear => :environment do 
That solved the problem and now the clear task doing its magic.

Toda Raba!

namespace :db do
    desc "clear the databse"
    task :clear => :environment do 
        User.delete_all
        Group.delete_all
        UsersGroup.delete_all
    end
end

**Comment by MikeSofaer** [comment]
Ein davar
